const HAS_LOCATION_RELATIONSHIP_LABEL = "HAS_LOCATION";
const OWNS_OR_CONTROLS_RELATIONSHIP_LABEL = "OWNS_OR_CONTROLS";
const LISTS_RELATIONSHIP_LABEL = "LISTS";
const OFFERS_PRODUCT_RELATIONSHIP_LABEL = "OFFERS_PRODUCT";
const SUPPLIES_COMPOUND_FORM_RELATIONSHIP_LABEL = "SUPPLIES_COMPOUND_FORM";
