export const HAS_LOCATION_RELATIONSHIP_LABEL = "HAS_LOCATION";
export const OWNS_OR_CONTROLS_RELATIONSHIP_LABEL = "OWNS_OR_CONTROLS";
export const LISTS_RELATIONSHIP_LABEL = "LISTS";
export const OFFERS_PRODUCT_RELATIONSHIP_LABEL = "OFFERS_PRODUCT";
export const SUPPLIES_COMPOUND_FORM_RELATIONSHIP_LABEL = "SUPPLIES_COMPOUND_FORM";
